version: '3.1'
services:

  divido-service-client-standalone:
    build: ./divido-service-client-standalone
    image: divido-service-client-standalone
    ports:
      - "8091:80"
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal var_display_max_depth=-1 var_display_max_children=-1 var_display_max_data=-1"