FROM phpstorm/php-71-apache-xdebug-27

RUN apt-get update -y && apt-get install -y libpng-dev curl libcurl4-openssl-dev

RUN docker-php-ext-install pdo pdo_mysql gd curl http

RUN a2enmod rewrite

RUN echo "\
xdebug.enable=1\n\
xdebug.remote_enable=1\n\
xdebug.remote_connect_back=0\n\
xdebug.remote_port=9000\n\
xdebug.idekey=\"PHPSTORM\"\n\
xdebug.extended_info=on\n\
xdebug.max_nesting_level=400\n\
xdebug.var_display_max_depth=-1\n\
">> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN service apache2 restart